# Generated by Django 4.0.6 on 2022-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='location',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
