# Generated by Django 4.0.6 on 2022-07-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='username',
            new_name='owner',
        ),
    ]
