# Generated by Django 4.0.6 on 2022-08-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapi', '0002_alter_profilemodel_bio_alter_profilemodel_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetmodel',
            name='content',
            field=models.TextField(max_length=160),
        ),
    ]
