# Generated by Django 4.0.6 on 2022-08-16 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweetapi', '0003_alter_tweetmodel_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetmodel',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
